import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <header style={{ padding: 20, background: "#f4f4f4" }}>
          <nav>
            <Link href="/" style={{ marginRight: 20 }}>
              Home
            </Link>
            <Link href="/about">About</Link>
            <Link href="/contact" style={{ marginLeft: 20 }}>
              Contact
            </Link>
            <Link href="/users" style={{ marginLeft: 20 }}>
              User
            </Link>
          </nav>
        </header>
        <main style={{ padding: 20 }}> {children}</main>
        <footer style={{ padding: 20, background: "#f4f4f4", marginTop: 40 }}>
          <p>© 2025 My Next App</p>
        </footer>
      </body>
    </html>
  );
}
